name: spacejam
description: SpaceJam is an open-sourced internal package used across the Mira Collection.
version: 1.1.7
homepage: https://www.kekesi.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  all_lint_rules_community: ^0.0.7
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter: